In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("train.csv")

In [4]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [6]:
df.shape

(1460, 81)

In [7]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [8]:
df.MSZoning.unique()

array(['RL', 'RM', 'C (all)', 'FV', 'RH'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
la=LabelEncoder().fit_transform(df.MSZoning)

In [11]:
df["MSZoning"]=la

In [12]:
df.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60         3         65.0     8450   Pave   NaN      Reg   
1   2          20         3         80.0     9600   Pave   NaN      Reg   
2   3          60         3         68.0    11250   Pave   NaN      IR1   
3   4          70         3         60.0     9550   Pave   NaN      IR1   
4   5          60         3         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [13]:
df.shape

(1460, 81)

In [14]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [15]:
df.fillna(0,inplace=True)

In [16]:
df.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60         3         65.0     8450   Pave     0      Reg   
1   2          20         3         80.0     9600   Pave     0      Reg   
2   3          60         3         68.0    11250   Pave     0      IR1   
3   4          70         3         60.0     9550   Pave     0      IR1   
4   5          60         3         84.0    14260   Pave     0      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0      0     0           0       0      2   
1         Lvl    AllPub  ...        0      0     0           0       0      5   
2         Lvl    AllPub  ...        0      0     0           0       0      9   
3         Lvl    AllPub  ...        0      0     0           0       0      2   
4         Lvl    AllPub  ...        0      0     0           0       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [17]:
df.shape

(1460, 81)

In [18]:
df1=df

In [19]:
df1.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60         3         65.0     8450   Pave     0      Reg   
1   2          20         3         80.0     9600   Pave     0      Reg   
2   3          60         3         68.0    11250   Pave     0      IR1   
3   4          70         3         60.0     9550   Pave     0      IR1   
4   5          60         3         84.0    14260   Pave     0      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0      0     0           0       0      2   
1         Lvl    AllPub  ...        0      0     0           0       0      5   
2         Lvl    AllPub  ...        0      0     0           0       0      9   
3         Lvl    AllPub  ...        0      0     0           0       0      2   
4         Lvl    AllPub  ...        0      0     0           0       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [20]:
ls=LabelEncoder().fit_transform(df1.Street)

In [21]:
df1["Street"]=ls

In [22]:
df1.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street Alley LotShape  \
0   1          60         3         65.0     8450       1     0      Reg   
1   2          20         3         80.0     9600       1     0      Reg   
2   3          60         3         68.0    11250       1     0      IR1   
3   4          70         3         60.0     9550       1     0      IR1   
4   5          60         3         84.0    14260       1     0      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0      0     0           0       0      2   
1         Lvl    AllPub  ...        0      0     0           0       0      5   
2         Lvl    AllPub  ...        0      0     0           0       0      9   
3         Lvl    AllPub  ...        0      0     0           0       0      2   
4         Lvl    AllPub  ...        0      0     0           0       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [23]:
ll=LabelEncoder().fit_transform(df1.LotShape)

In [24]:
df1["LotShape"]=ll

In [25]:
ln=LabelEncoder().fit_transform(df1.LandContour)

In [26]:
df1["LandContour"]=ln

In [27]:
df1.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street Alley  LotShape  \
0   1          60         3         65.0     8450       1     0         3   
1   2          20         3         80.0     9600       1     0         3   
2   3          60         3         68.0    11250       1     0         0   
3   4          70         3         60.0     9550       1     0         0   
4   5          60         3         84.0    14260       1     0         0   

   LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
0            3    AllPub  ...        0      0     0           0       0   
1            3    AllPub  ...        0      0     0           0       0   
2            3    AllPub  ...        0      0     0           0       0   
3            3    AllPub  ...        0      0     0           0       0   
4            3    AllPub  ...        0      0     0           0       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [28]:
un=LabelEncoder().fit_transform(df1.Utilities)

In [29]:
df1["Utilities"]=un

In [30]:
df1.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street Alley  LotShape  \
0   1          60         3         65.0     8450       1     0         3   
1   2          20         3         80.0     9600       1     0         3   
2   3          60         3         68.0    11250       1     0         0   
3   4          70         3         60.0     9550       1     0         0   
4   5          60         3         84.0    14260       1     0         0   

   LandContour  Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
0            3          0  ...        0      0     0           0       0   
1            3          0  ...        0      0     0           0       0   
2            3          0  ...        0      0     0           0       0   
3            3          0  ...        0      0     0           0       0   
4            3          0  ...        0      0     0           0       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [31]:
sa=LabelEncoder().fit_transform(df1.SaleType)

In [32]:
df1["SaleType"]=sa

In [33]:
sl=LabelEncoder().fit_transform(df1.SaleCondition)

In [34]:
df1["SaleCondition"]=sl

In [35]:
df1.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street Alley  LotShape  \
0   1          60         3         65.0     8450       1     0         3   
1   2          20         3         80.0     9600       1     0         3   
2   3          60         3         68.0    11250       1     0         0   
3   4          70         3         60.0     9550       1     0         0   
4   5          60         3         84.0    14260       1     0         0   

   LandContour  Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
0            3          0  ...        0      0     0           0       0   
1            3          0  ...        0      0     0           0       0   
2            3          0  ...        0      0     0           0       0   
3            3          0  ...        0      0     0           0       0   
4            3          0  ...        0      0     0           0       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008         8              4     208500  
1      5   2007         8              4     181500  
2      9   2008         8              4     223500  
3      2   2006         8              0     140000  
4     12   2008         8              4     250000  

[5 rows x 81 columns]

In [36]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   Alley          1460 non-null   object 
 7   LotShape       1460 non-null   int32  
 8   LandContour    1460 non-null   int32  
 9   Utilities      1460 non-null   int32  
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [37]:
df["Alley"].unique()

array([0, 'Grvl', 'Pave'], dtype=object)

In [38]:
dum=pd.get_dummies(df1.Alley)

In [39]:
dum

0  Grvl  Pave
0     1     0     0
1     1     0     0
2     1     0     0
3     1     0     0
4     1     0     0
...  ..   ...   ...
1455  1     0     0
1456  1     0     0
1457  1     0     0
1458  1     0     0
1459  1     0     0

[1460 rows x 3 columns]

In [40]:
df2=pd.concat([df1,dum],axis=1)

In [41]:
df2.shape

(1460, 84)

In [42]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street Alley  LotShape  \
0   1          60         3         65.0     8450       1     0         3   
1   2          20         3         80.0     9600       1     0         3   
2   3          60         3         68.0    11250       1     0         0   
3   4          70         3         60.0     9550       1     0         0   
4   5          60         3         84.0    14260       1     0         0   

   LandContour  Utilities  ... MiscFeature MiscVal MoSold YrSold SaleType  \
0            3          0  ...           0       0      2   2008        8   
1            3          0  ...           0       0      5   2007        8   
2            3          0  ...           0       0      9   2008        8   
3            3          0  ...           0       0      2   2006        8   
4            3          0  ...           0       0     12   2008        8   

  SaleCondition SalePrice  0  Grvl  Pave  
0             4    208500  1     0     0  
1             4    181500  1     0     0  
2             4    223500  1     0     0  
3             0    140000  1     0     0  
4             4    250000  1     0     0  

[5 rows x 84 columns]

In [43]:
df2.drop(["Grvl"],axis=1,inplace=True)

In [44]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street Alley  LotShape  \
0   1          60         3         65.0     8450       1     0         3   
1   2          20         3         80.0     9600       1     0         3   
2   3          60         3         68.0    11250       1     0         0   
3   4          70         3         60.0     9550       1     0         0   
4   5          60         3         84.0    14260       1     0         0   

   LandContour  Utilities  ... Fence MiscFeature MiscVal MoSold YrSold  \
0            3          0  ...     0           0       0      2   2008   
1            3          0  ...     0           0       0      5   2007   
2            3          0  ...     0           0       0      9   2008   
3            3          0  ...     0           0       0      2   2006   
4            3          0  ...     0           0       0     12   2008   

  SaleType SaleCondition  SalePrice  0  Pave  
0        8             4     208500  1     0  
1        8             4     181500  1     0  
2        8             4     223500  1     0  
3        8             0     140000  1     0  
4        8             4     250000  1     0  

[5 rows x 83 columns]

In [45]:
df2.shape

(1460, 83)

In [46]:
df2.drop("Alley",axis=1,inplace=True)

In [47]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 82 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   int32  
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   object 
 10  LandSlope      1460 non-null   object 
 11  Neighborhood   1460 non-null   object 
 12  Condition1     1460 non-null   object 
 13  Condition2     1460 non-null   object 
 14  BldgType       1460 non-null   object 
 15  HouseStyle     1460 non-null   object 
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [48]:
lo=LabelEncoder().fit_transform(df2.LotConfig)

In [49]:
df2["LotConfig"]=lo

In [50]:
ld=LabelEncoder().fit_transform(df2.LandSlope)

In [51]:
df2["LandSlope"]=ld

In [52]:
ne=LabelEncoder().fit_transform(df2.Neighborhood)

In [53]:
df2["Neighborhood"]=ne

In [54]:
co=LabelEncoder().fit_transform(df2.Condition1)

In [55]:
df2["Condition1"]=co

In [56]:
con=LabelEncoder().fit_transform(df2.Condition2)

In [57]:
df2["Condition2"]=con

In [58]:
bl=LabelEncoder().fit_transform(df2.BldgType)

In [59]:
df2["BldgType"]=bl

In [60]:
ho=LabelEncoder().fit_transform(df2.HouseStyle)

In [61]:
df2["HouseStyle"]=ho

In [62]:
ro=LabelEncoder().fit_transform(df2.RoofStyle)

In [63]:
df2["RoofStyle"]=ro

In [64]:
rm=LabelEncoder().fit_transform(df2.RoofMatl)

In [65]:
df2["RoofMatl"]=rm

In [66]:
ex=LabelEncoder().fit_transform(df2.Exterior1st)

In [67]:
df2["Exterior1st"]=ex

In [68]:
ex2=LabelEncoder().fit_transform(df2.Exterior2nd)

In [69]:
df2["Exterior2nd"]=ex2

In [70]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1         3   
1   2          20         3         80.0     9600       1         3   
2   3          60         3         68.0    11250       1         0   
3   4          70         3         60.0     9550       1         0   
4   5          60         3         84.0    14260       1         0   

   LandContour  Utilities  LotConfig  ...  Fence  MiscFeature  MiscVal  \
0            3          0          4  ...      0            0        0   
1            3          0          2  ...      0            0        0   
2            3          0          4  ...      0            0        0   
3            3          0          0  ...      0            0        0   
4            3          0          2  ...      0            0        0   

   MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  Pave  
0       2    2008         8              4     208500  1     0  
1       5    2007         8              4     181500  1     0  
2       9    2008         8              4     223500  1     0  
3       2    2006         8              0     140000  1     0  
4      12    2008         8              4     250000  1     0  

[5 rows x 82 columns]

In [71]:
df2.drop("Pave",axis=1,inplace=True)

In [72]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1         3   
1   2          20         3         80.0     9600       1         3   
2   3          60         3         68.0    11250       1         0   
3   4          70         3         60.0     9550       1         0   
4   5          60         3         84.0    14260       1         0   

   LandContour  Utilities  LotConfig  ...  PoolQC  Fence  MiscFeature  \
0            3          0          4  ...       0      0            0   
1            3          0          2  ...       0      0            0   
2            3          0          4  ...       0      0            0   
3            3          0          0  ...       0      0            0   
4            3          0          2  ...       0      0            0   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  
0        0       2    2008         8              4     208500  1  
1        0       5    2007         8              4     181500  1  
2        0       9    2008         8              4     223500  1  
3        0       2    2006         8              0     140000  1  
4        0      12    2008         8              4     250000  1  

[5 rows x 81 columns]

In [73]:
df2["MiscFeature"].unique()

array([0, 'Shed', 'Gar2', 'Othr', 'TenC'], dtype=object)

In [74]:
df2["MiscFeature"]=df2["MiscFeature"].str.replace("Shed","1")

In [75]:
df2["MiscFeature"].unique()

array([nan, '1', 'Gar2', 'Othr', 'TenC'], dtype=object)

In [76]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1         3   
1   2          20         3         80.0     9600       1         3   
2   3          60         3         68.0    11250       1         0   
3   4          70         3         60.0     9550       1         0   
4   5          60         3         84.0    14260       1         0   

   LandContour  Utilities  LotConfig  ...  PoolQC  Fence  MiscFeature  \
0            3          0          4  ...       0      0          NaN   
1            3          0          2  ...       0      0          NaN   
2            3          0          4  ...       0      0          NaN   
3            3          0          0  ...       0      0          NaN   
4            3          0          2  ...       0      0          NaN   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  
0        0       2    2008         8              4     208500  1  
1        0       5    2007         8              4     181500  1  
2        0       9    2008         8              4     223500  1  
3        0       2    2006         8              0     140000  1  
4        0      12    2008         8              4     250000  1  

[5 rows x 81 columns]

In [77]:
df2["MiscFeature"]=df2["MiscFeature"].str.replace("Gar2","2")

In [78]:
df2["MiscFeature"]=df2["MiscFeature"].str.replace("TenC","3")

In [79]:
df2["MiscFeature"].unique()

array([nan, '1', '2', 'Othr', '3'], dtype=object)

In [80]:
df2.isna().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
0                0
Length: 81, dtype: int64

In [81]:
df2.fillna(0,inplace=True)

In [82]:
df2["MiscFeature"].unique()

array([0, '1', '2', 'Othr', '3'], dtype=object)

In [83]:
df2["MiscFeature"].value_counts()

0       1406
1         49
2          2
Othr       2
3          1
Name: MiscFeature, dtype: int64

In [84]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1         3   
1   2          20         3         80.0     9600       1         3   
2   3          60         3         68.0    11250       1         0   
3   4          70         3         60.0     9550       1         0   
4   5          60         3         84.0    14260       1         0   

   LandContour  Utilities  LotConfig  ...  PoolQC  Fence  MiscFeature  \
0            3          0          4  ...       0      0            0   
1            3          0          2  ...       0      0            0   
2            3          0          4  ...       0      0            0   
3            3          0          0  ...       0      0            0   
4            3          0          2  ...       0      0            0   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  
0        0       2    2008         8              4     208500  1  
1        0       5    2007         8              4     181500  1  
2        0       9    2008         8              4     223500  1  
3        0       2    2006         8              0     140000  1  
4        0      12    2008         8              4     250000  1  

[5 rows x 81 columns]

In [85]:
df2["LotShape"]=df2.LotShape.astype(float)

In [86]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1       3.0   
1   2          20         3         80.0     9600       1       3.0   
2   3          60         3         68.0    11250       1       0.0   
3   4          70         3         60.0     9550       1       0.0   
4   5          60         3         84.0    14260       1       0.0   

   LandContour  Utilities  LotConfig  ...  PoolQC  Fence  MiscFeature  \
0            3          0          4  ...       0      0            0   
1            3          0          2  ...       0      0            0   
2            3          0          4  ...       0      0            0   
3            3          0          0  ...       0      0            0   
4            3          0          2  ...       0      0            0   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  
0        0       2    2008         8              4     208500  1  
1        0       5    2007         8              4     181500  1  
2        0       9    2008         8              4     223500  1  
3        0       2    2006         8              0     140000  1  
4        0      12    2008         8              4     250000  1  

[5 rows x 81 columns]

In [87]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   float64
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   int32  
 10  LandSlope      1460 non-null   int32  
 11  Neighborhood   1460 non-null   int32  
 12  Condition1     1460 non-null   int32  
 13  Condition2     1460 non-null   int32  
 14  BldgType       1460 non-null   int32  
 15  HouseStyle     1460 non-null   int32  
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [88]:
df2["MasVnrType"].unique()

array(['BrkFace', 'None', 'Stone', 'BrkCmn', 0], dtype=object)

In [89]:
df2["MasVnrType"]=df2["MasVnrType"].str.replace("0","End")

In [90]:
df2.MasVnrType.unique()

array(['BrkFace', 'None', 'Stone', 'BrkCmn', nan], dtype=object)

In [91]:
aa=LabelEncoder().fit_transform(df2.MasVnrType)

In [92]:
df2["MasVnrType"]=aa

In [93]:
df2.MasVnrType.unique()

array([1, 2, 3, 0, 4])

In [94]:
bb=LabelEncoder().fit_transform(df2.ExterQual)

In [95]:
df2["ExterQual"]=bb

In [96]:
cc=LabelEncoder().fit_transform(df2.ExterCond)

In [97]:
df2["ExterCond"]=cc

In [98]:
dd=LabelEncoder().fit_transform(df2.Foundation)

In [99]:
df2["Foundation"]=dd

In [100]:
df2["BsmtQual"]=df2["BsmtQual"].str.replace("0","last")

In [101]:
df2["BsmtQual"].unique()

array(['Gd', 'TA', 'Ex', nan, 'Fa'], dtype=object)

In [102]:
ee=LabelEncoder().fit_transform(df2.BsmtQual)

In [103]:
df2["BsmtQual"]=ee

In [104]:
df2.BsmtCond.unique()

array(['TA', 'Gd', 0, 'Fa', 'Po'], dtype=object)

In [105]:
df2["BsmtCond"]=df2["BsmtCond"].str.replace("0","Last")

In [106]:
ff=LabelEncoder().fit_transform(df2.BsmtCond)

In [107]:
df2["BsmtCond"]=ff

In [108]:
df2["BsmtExposure"].unique()

array(['No', 'Gd', 'Mn', 'Av', 0], dtype=object)

In [109]:
df2["BsmtExposure"]=df2["BsmtExposure"].str.replace("0","last")

In [110]:
gg=LabelEncoder().fit_transform(df2.BsmtExposure)

In [111]:
df2["BsmtExposure"]=gg

In [112]:
df2["BsmtFinType1"].unique()

array(['GLQ', 'ALQ', 'Unf', 'Rec', 'BLQ', 0, 'LwQ'], dtype=object)

In [113]:
df2["BsmtFinType1"]=df2["BsmtFinType1"].str.replace("0"," ")

In [114]:
hh=LabelEncoder().fit_transform(df2.BsmtFinType1)

In [115]:
df2["BsmtFinType1"]=hh

In [116]:
df2["BsmtFinType2"].unique()

array(['Unf', 'BLQ', 0, 'ALQ', 'Rec', 'LwQ', 'GLQ'], dtype=object)

In [117]:
df2["BsmtFinType2"]=df2["BsmtFinType2"].str.replace("0"," ")

In [118]:
ii=LabelEncoder().fit_transform(df2.BsmtFinType2)

In [119]:
df2["BsmtFinType2"]=ii

In [120]:
df2["Heating"].unique()

array(['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'], dtype=object)

In [121]:
jj=LabelEncoder().fit_transform(df2.Heating)

In [122]:
df2["Heating"]=jj

In [123]:
df2["HeatingQC"].unique()

array(['Ex', 'Gd', 'TA', 'Fa', 'Po'], dtype=object)

In [124]:
kk=LabelEncoder().fit_transform(df2.HeatingQC)

In [125]:
df2["HeatingQC"]=kk

In [126]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   float64
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   int32  
 10  LandSlope      1460 non-null   int32  
 11  Neighborhood   1460 non-null   int32  
 12  Condition1     1460 non-null   int32  
 13  Condition2     1460 non-null   int32  
 14  BldgType       1460 non-null   int32  
 15  HouseStyle     1460 non-null   int32  
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [127]:
df2["CentralAir"].unique()

array(['Y', 'N'], dtype=object)

In [128]:
ll=LabelEncoder().fit_transform(df2.CentralAir)

In [129]:
df2["CentralAir"]=ll

In [130]:
df2["Electrical"].unique()

array(['SBrkr', 'FuseF', 'FuseA', 'FuseP', 'Mix', 0], dtype=object)

In [131]:
df2["Electrical"]=df2["Electrical"].str.replace("0"," ")

In [132]:
mm=LabelEncoder().fit_transform(df2.Electrical)

In [133]:
df2["Electrical"]=mm

In [134]:
df2["KitchenQual"].unique()

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [135]:
nn=LabelEncoder().fit_transform(df2.KitchenQual)

In [136]:
df2["Functional"].unique()

array(['Typ', 'Min1', 'Maj1', 'Min2', 'Mod', 'Maj2', 'Sev'], dtype=object)

In [137]:
oo=LabelEncoder().fit_transform(df2.Functional)

In [138]:
df2["Functional"]=oo

In [139]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1       3.0   
1   2          20         3         80.0     9600       1       3.0   
2   3          60         3         68.0    11250       1       0.0   
3   4          70         3         60.0     9550       1       0.0   
4   5          60         3         84.0    14260       1       0.0   

   LandContour  Utilities  LotConfig  ...  PoolQC  Fence  MiscFeature  \
0            3          0          4  ...       0      0            0   
1            3          0          2  ...       0      0            0   
2            3          0          4  ...       0      0            0   
3            3          0          0  ...       0      0            0   
4            3          0          2  ...       0      0            0   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  
0        0       2    2008         8              4     208500  1  
1        0       5    2007         8              4     181500  1  
2        0       9    2008         8              4     223500  1  
3        0       2    2006         8              0     140000  1  
4        0      12    2008         8              4     250000  1  

[5 rows x 81 columns]

In [140]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   float64
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   int32  
 10  LandSlope      1460 non-null   int32  
 11  Neighborhood   1460 non-null   int32  
 12  Condition1     1460 non-null   int32  
 13  Condition2     1460 non-null   int32  
 14  BldgType       1460 non-null   int32  
 15  HouseStyle     1460 non-null   int32  
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [141]:
df2["KitchenQual"].unique()

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [142]:
ki=LabelEncoder().fit_transform(df2.KitchenQual)

In [143]:
df2["KitchenQual"]=ki

In [144]:
df2["FireplaceQu"].unique()

array([0, 'TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [145]:
df2["FireplaceQu"]=df2["FireplaceQu"].str.replace("0","end")

In [146]:
df2.FireplaceQu.unique()

array([nan, 'TA', 'Gd', 'Fa', 'Ex', 'Po'], dtype=object)

In [147]:
fii=LabelEncoder().fit_transform(df2.FireplaceQu)

In [148]:
df2["FireplaceQu"]=fii

In [149]:
df2.GarageType.unique()

array(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', 0, 'Basment', '2Types'],
      dtype=object)

In [150]:
df2["GarageType"]=df2.GarageType.str.replace("0","nan")

In [151]:
df2["GarageType"]=df2.GarageType.str.replace("2Types","nan")

In [152]:
Ga=LabelEncoder().fit_transform(df2.GarageType)

In [153]:
df2["GarageType"]=Ga

In [154]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   float64
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   int32  
 10  LandSlope      1460 non-null   int32  
 11  Neighborhood   1460 non-null   int32  
 12  Condition1     1460 non-null   int32  
 13  Condition2     1460 non-null   int32  
 14  BldgType       1460 non-null   int32  
 15  HouseStyle     1460 non-null   int32  
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [155]:
df2["GarageFinish"].unique()

array(['RFn', 'Unf', 'Fin', 0], dtype=object)

In [156]:
df2["GarageFinish"]=df2["GarageFinish"].str.replace("0","nan")

In [157]:
Gr=LabelEncoder().fit_transform(df2.GarageFinish)

In [158]:
df2["GarageFinish"]=Gr

In [159]:
df2["GarageQual"].unique()

array(['TA', 'Fa', 'Gd', 0, 'Ex', 'Po'], dtype=object)

In [160]:
df2["GarageQual"]=df2["GarageQual"].str.replace("0","end")

In [161]:
G1=LabelEncoder().fit_transform(df2.GarageQual)

In [162]:
df2["GarageQual"]=G1

In [163]:
df2["GarageCond"].unique()

array(['TA', 'Fa', 0, 'Gd', 'Po', 'Ex'], dtype=object)

In [164]:
df2["GarageCond"]=df2["GarageCond"].str.replace("0","end")

In [165]:
G2=LabelEncoder().fit_transform(df2.GarageCond)

In [166]:
df2["GarageCond"]=G2

In [167]:
df2["PavedDrive"].unique()

array(['Y', 'N', 'P'], dtype=object)

In [168]:
G3=LabelEncoder().fit_transform(df2.PavedDrive)

In [169]:
df2["PavedDrive"]=G3

In [170]:
df2["PoolQC"].unique()

array([0, 'Ex', 'Fa', 'Gd'], dtype=object)

In [171]:
df2["PoolQC"]=df2["PoolQC"].str.replace("0","end")

In [172]:
G4=LabelEncoder().fit_transform(df2.PoolQC)

In [173]:
df2["PoolQC"]=G4

In [174]:
df2["Fence"].unique()

array([0, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], dtype=object)

In [175]:
df2["Fence"]=df2.Fence.str.replace("0","end")

In [176]:
df2["Fence"].unique()

array([nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw'], dtype=object)

In [177]:
G5=LabelEncoder().fit_transform(df2.Fence)

In [178]:
df2["Fence"]=G5

In [179]:
df2["MiscFeature"]=df2["MiscFeature"].replace("Othr","4")

In [180]:
df2["MiscFeature"].unique()

array([0, '1', '2', '4', '3'], dtype=object)

In [181]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   float64
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   int32  
 10  LandSlope      1460 non-null   int32  
 11  Neighborhood   1460 non-null   int32  
 12  Condition1     1460 non-null   int32  
 13  Condition2     1460 non-null   int32  
 14  BldgType       1460 non-null   int32  
 15  HouseStyle     1460 non-null   int32  
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [182]:
df2.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         3         65.0     8450       1       3.0   
1   2          20         3         80.0     9600       1       3.0   
2   3          60         3         68.0    11250       1       0.0   
3   4          70         3         60.0     9550       1       0.0   
4   5          60         3         84.0    14260       1       0.0   

   LandContour  Utilities  LotConfig  ...  PoolQC  Fence  MiscFeature  \
0            3          0          4  ...       3      4            0   
1            3          0          2  ...       3      4            0   
2            3          0          4  ...       3      4            0   
3            3          0          0  ...       3      4            0   
4            3          0          2  ...       3      4            0   

   MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  0  
0        0       2    2008         8              4     208500  1  
1        0       5    2007         8              4     181500  1  
2        0       9    2008         8              4     223500  1  
3        0       2    2006         8              0     140000  1  
4        0      12    2008         8              4     250000  1  

[5 rows x 81 columns]

In [183]:
Lebels=df2["SalePrice"]

In [184]:
data=df2.drop("SalePrice",axis=1)

In [185]:
df2.shape

(1460, 81)

In [186]:
from sklearn.model_selection import train_test_split

In [187]:
x_train,x_test,y_train,y_test=train_test_split(data,Lebels,test_size=0.2,random_state=42)

In [188]:
x_train.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
254    255          20         3         70.0     8400       1       3.0   
1066  1067          60         3         59.0     7837       1       0.0   
638    639          30         3         67.0     8777       1       3.0   
799    800          50         3         60.0     7200       1       3.0   
380    381          50         3         50.0     5000       1       3.0   

      LandContour  Utilities  LotConfig  ...  PoolArea  PoolQC  Fence  \
254             3          0          4  ...         0       3      4   
1066            3          0          4  ...         0       3      4   
638             3          0          4  ...         0       3      2   
799             3          0          0  ...         0       3      2   
380             3          0          4  ...         0       3      4   

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  0  
254             0        0       6    2010         8              4  1  
1066            0        0       5    2009         8              4  1  
638             0        0       5    2008         8              4  1  
799             0        0       6    2007         8              4  1  
380             0        0       5    2010         8              4  0  

[5 rows x 80 columns]

In [189]:
y_train.head

<bound method NDFrame.head of 254     145000
1066    178000
638      85000
799     175000
380     127000
         ...  
1095    176432
1130    135000
1294    115000
860     189950
1126    174000
Name: SalePrice, Length: 1168, dtype: int64>

In [190]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   LotShape       1460 non-null   float64
 7   LandContour    1460 non-null   int32  
 8   Utilities      1460 non-null   int32  
 9   LotConfig      1460 non-null   int32  
 10  LandSlope      1460 non-null   int32  
 11  Neighborhood   1460 non-null   int32  
 12  Condition1     1460 non-null   int32  
 13  Condition2     1460 non-null   int32  
 14  BldgType       1460 non-null   int32  
 15  HouseStyle     1460 non-null   int32  
 16  OverallQual    1460 non-null   int64  
 17  OverallCond    1460 non-null   int64  
 18  YearBuil

In [223]:
df2.shape

(1460, 81)

In [191]:
from sklearn.linear_model import LinearRegression

In [192]:
model=LinearRegression()

In [193]:
model.fit(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


LinearRegression()

In [194]:
df2.describe()

Id   MSSubClass     MSZoning  LotFrontage        LotArea  \
count  1460.000000  1460.000000  1460.000000  1460.000000    1460.000000   
mean    730.500000    56.897260     3.028767    57.623288   10516.828082   
std     421.610009    42.300571     0.632017    34.664304    9981.264932   
min       1.000000    20.000000     0.000000     0.000000    1300.000000   
25%     365.750000    20.000000     3.000000    42.000000    7553.500000   
50%     730.500000    50.000000     3.000000    63.000000    9478.500000   
75%    1095.250000    70.000000     3.000000    79.000000   11601.500000   
max    1460.000000   190.000000     4.000000   313.000000  215245.000000   

            Street     LotShape  LandContour    Utilities    LotConfig  ...  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000  ...   
mean      0.995890     1.942466     2.777397     0.000685     3.019178  ...   
std       0.063996     1.409156     0.707666     0.026171     1.622634  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       1.000000     0.000000     3.000000     0.000000     2.000000  ...   
50%       1.000000     3.000000     3.000000     0.000000     4.000000  ...   
75%       1.000000     3.000000     3.000000     0.000000     4.000000  ...   
max       1.000000     3.000000     3.000000     1.000000     4.000000  ...   

          PoolArea       PoolQC        Fence       MiscVal       MoSold  \
count  1460.000000  1460.000000  1460.000000   1460.000000  1460.000000   
mean      2.758904     2.991096     3.504795     43.489041     6.321918   
std      40.177307     0.140703     1.082912    496.123024     2.703626   
min       0.000000     0.000000     0.000000      0.000000     1.000000   
25%       0.000000     3.000000     4.000000      0.000000     5.000000   
50%       0.000000     3.000000     4.000000      0.000000     6.000000   
75%       0.000000     3.000000     4.000000      0.000000     8.000000   
max     738.000000     3.000000     4.000000  15500.000000    12.000000   

            YrSold     SaleType  SaleCondition      SalePrice            0  
count  1460.000000  1460.000000    1460.000000    1460.000000  1460.000000  
mean   2007.815753     7.513014       3.770548  180921.195890     0.937671  
std       1.328095     1.552100       1.100854   79442.502883     0.241835  
min    2006.000000     0.000000       0.000000   34900.000000     0.000000  
25%    2007.000000     8.000000       4.000000  129975.000000     1.000000  
50%    2008.000000     8.000000       4.000000  163000.000000     1.000000  
75%    2009.000000     8.000000       4.000000  214000.000000     1.000000  
max    2010.000000     8.000000       5.000000  755000.000000     1.000000  

[8 rows x 80 columns]

In [195]:
pred=model.predict(x_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [224]:
pred

array([147177.79796169, 316010.45535268, 109533.13243686, 175798.86853737,
       319990.97441061,  78393.73768455, 234734.43482414, 140546.53323716,
        77493.74509056, 151646.38373888, 148422.00577356, 102993.07463683,
        82408.86785759, 205646.58937772, 167663.7118162 , 133198.90859229,
       210107.9244551 , 116010.55191584, 108966.91887738, 228952.41792317,
       136375.83893777, 208714.53016268, 186064.77132385, 119344.9778632 ,
       213057.31065186, 161215.12137507, 206853.60595437,  84936.99891968,
       166105.41753479, 191052.43877033, 171869.03846032, 261871.27498381,
       196271.1588773 , 103693.6014621 , 261304.61303158, 149004.88346349,
       117000.88406983, 214769.55763415, 290918.98244532,  91226.34101953,
       113346.56687403, 252612.31368357, 105056.20165009, 321645.23654629,
       132008.56382045, 151650.99282833,  90593.28427607, 132231.40362282,
       394474.71835391, 126813.4535456 , 111902.46066061, 216384.11358672,
       112654.07978801, 3

In [196]:
from sklearn.metrics import mean_squared_error

In [197]:
mse=mean_squared_error(y_test,pred)

In [198]:
mse

1160557171.4024546

In [199]:
np.sqrt(mse)

34066.95130771837

In [200]:
model.score(x_test,y_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8486952001708861

In [201]:
model.score(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8527138869829377

In [202]:
from sklearn.linear_model import Lasso

In [203]:
La=Lasso().fit(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.038e+10, tolerance: 6.967e+08
  model = cd_fast.enet_coordinate_descent(


In [204]:
La.score(x_test,y_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8487124912318291

In [205]:
La.score(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8527135168110496

In [206]:
from sklearn.linear_model import Ridge

In [207]:
Ri=Ridge().fit(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [208]:
Ri.score(x_test,y_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8499608391427911

In [209]:
Ri.score(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8523798830104776

In [210]:
from sklearn.svm import SVC

In [211]:
sv=SVC().fit(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [212]:
sv.score(x_test,y_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.017123287671232876

In [213]:
from sklearn.tree import DecisionTreeRegressor

In [214]:
De=DecisionTreeRegressor().fit(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [215]:
De.score(x_test,y_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.7707914658804917

In [216]:
De.score(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


1.0

In [217]:
from sklearn.ensemble import RandomForestRegressor

In [218]:
Ra=RandomForestRegressor().fit(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [219]:
Ra.score(x_test,y_test)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.8977791992704367

In [220]:
Ra.score(x_train,y_train)

C:\Users\vikram kumar\AppData\Local\Programs\Python\Python39-32\lib\site-packages\sklearn\utils\validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.9776545775408795

In [221]:
from joblib import dump,load

In [222]:
dump(Ra,"model1")

['model1']